### ISSUE TITLE
filename containing 'username' or 'password' causes crash

### ISSUE THREAD

**Issue by ColmMcBarron** [gordonwritescode/gitty#35]
Noticed recently when doing a git pull via gitty, the app crashes, complaining about creds.pass.

I've isolated it to the following piece of code in classes/repository.js

    function sync(path, operation, remote, branch, flags, callback, creds) {
        var operations = [operation, remote, branch].concat(flags || [])
          , pterm = pty.spawn('git', operations, { cwd : path })
          , repo = this
          , err
          , succ;
        pterm.on('data', function(data) {
                var prompt = data.toLowerCase();
                if (prompt.indexOf('username') > -1) {
                        pterm.write(creds.user + '\r');
                } else if (prompt.indexOf('password') > -1) {
                      pterm.write(creds.pass + '\r');
                } else if ((prompt.indexOf('error') > -1) || (prompt.indexOf('fatal') > -1)) {
                      err = parse['syncErr'](prompt);
                } else {
                        succ = parse['syncSuccess'](prompt);
                }
        });
        pterm.on('exit', function() {
                if (callback && typeof callback === 'function') callback.call(repo, err, succ);
        });
    };

If I comment out the lines creds,user and creds.pass it works perfectly. Further investigation, it seems that it was stalling during printing the files changed in the git commit, in particular with a file called 'passwordStrengthMeter.css', so was picking up the string 'password' and assuming it was a password request. I assume this would also be a problem for 'username' as well.

I'm not sure what the fix would be here, for now I've just commented out the offending line.

**Comment by gordonwritescode** [comment]
Sorry for such a late response, this issue was submitted 2 days after my daughter was born and was forgotten. Gitty has undergone substantial changes since then, but I think this problem will still manifest:

https://github.com/gordonwritescode/gitty/blob/master/index.js#L88-L102

There certainly must be a more deterministic way to detect a username/password request - i will give it some thought.

**Comment by ColmMcBarron** [comment]
@gordonwritescode totally understandable and congrats!

I've also recently entered the world of fatherhood so I know what must take priority :-)

**Comment by gordonwritescode** [comment]
This may seem like a cop-out, but the fix for this was to no longer support username/password authentication over SSH - folks should be using SSH keys for that. Now authentication is up to the user to ensure is implemented properly.
