### ISSUE TITLE
can't modify Repository prototype when requiring gitty

### ISSUE THREAD

**Issue by pyramation** [gordonwritescode/gitty#36]
I am trying to upgrade from 1.2.6 to 3.1.1, but realizing that extending the prototype is not as straight forward anymore. Is it possible to modify a Repository prototype by simply requiring gitty?

The old way you could simply do

```js

var git = require('gitty');
git.Repository.prototype.myNewMethod = function() {}
```

Now it looks like the `Command` and `Repository` are completely hidden from the developer who uses `require('gitty')`. Seems like the module returns a class that instantiates a new `Repository` when you instantiate a new `gitty` object.

Please let me know if I'm missing something here, but I'd love to modify the prototypes without forking gitty :)

**Comment by pyramation** [comment]
I created a pull request https://github.com/gordonwritescode/gitty/pull/37 for this issue

**Comment by gordonwritescode** [comment]
closing, since PR was merged
