### ISSUE TITLE
Error when trying to run log command

### ISSUE THREAD

**Issue by adriangordon1231** [gordonwritescode/gitty#49]
I am currently attempting to use three functions in this library, pull, log and reset. Unfortunately however, every time I try to run either log or reset I get this error: 

undefined:1
['{commit:cdaf988823cc900c4caaa1e30c16d6dd10854f9a,author:Adrian Gordon
 ^
SyntaxError: Unexpected token '

Any clue as to why this is happening?

**Comment by gordonwritescode** [comment]
Looks like an issue with the output parser getting an invalid JSON string. We need to reassess the way we form the JSON output from the log method. Will look into it, thanks for the report.

**Comment by adriangordon1231** [comment]
No problem.

**Comment by gordonwritescode** [comment]
Closed by #53
