### ISSUE TITLE
Add configuration to specify path to git binary

### ISSUE THREAD

**Issue by waynebloss** [gordonwritescode/gitty#51]
It looks like your command lib uses the globally installed git (or, whatever is in the current working directory I presume).

Would you consider adding (or accepting a pull request for) a configuration option to specify the path to git?

**Comment by gordonwritescode** [comment]
Absolutely. Ideally I think `Repository` should take a second options argument that can specify a `gitpath` property or similar. That property I suppose would get handed to each instantiated `Command` object.

But, of course I am open to whatever you come up with. Cheers!

**Comment by waynebloss** [comment]
How do you feel about, passing just `self` to `new Command` everywhere, instead of `self.path`? And then the `Command` constructor would just access them as `repo.path | gitpath` or maybe something like `spec.path | gitpath` (where `spec` represents a specification for the command, which includes the 2 fields (`path` and `gitpath`) that will now always be passed to new up a `Command`).

*To complete the transformation, I would also rename the `this.repo` field inside of `Command` to `this.repopath` and then add `this.gitpath` as a separate field. Alternatively, we could save `spec` into `this.spec` and just use that directly.*

If you don't like any of that, no problem - just tell me how you would like the `gitpath` passed to each `new Command` and then stored inside the `Command` instance? It's a little bit of code and I probably spent more time writing this message than I could have just typing the code, so if you're not entirely sure of what I'm talking about just let me know and I'll do the pull request so you can see the result.

**Comment by waynebloss** [comment]
I think I would personally lean towards calling the first argument of `new Command` `repo` and storing it as `this.repo` inside of `Command` since that's what would be getting passed...and then use `this.repo.path` wherever I needed and `this.repo.gitpath` wherever I needed.

**Comment by gordonwritescode** [comment]
I don't have any objections to what you described, it sounds completely reasonable. I'll take some time tomorrow to review #52. 

Cheers!

**Comment by gordonwritescode** [comment]
Merged #52 , added test, bumped version to 3.3.1, and published to NPM
